import type { Metadata } from "next";
import "./globals.css";
import { Header, ThemeProvider, ThemeButton } from '@/components';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html className="scroll-pt-[3.5rem]">
            <body>
                <Header />
                <main className="pt-[90px] flex justify-center">
                    {children}
                </main>
                <ThemeProvider attribute="class" enableSystem disableTransitionOnChange>
                    <ThemeButton />
                </ThemeProvider>
            </body>
        </html>
    );
}
